/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lists.listaPedidos;
import pi.pedidos;
import pi.produto;

/**
 *
 * @author Pichau
 */
public class MainMenu extends javax.swing.JFrame {

   List<pedidos> listapd =listaPedidos.listar();
   String[] colunas={"N°Pedido", "Produto","Cliente","Qtd","Status","Data de entrega"};
    
   
   public int getrow(){
      
     
          int index = tabela.getSelectedRow();
       
     pedidos ped=  listapd.get(index);
       
       return ped.getN_pedido();
     
       
      
    
   }
 public void addpedido(){
        
        if(!listapd.isEmpty()){
        DefaultTableModel tableModel = new DefaultTableModel(colunas, 0);
         tabela.setModel(tableModel);

           for(int i=0;i<listapd.size();i++){
            
            pedidos pd= listapd.get(i);
            String num =""+pd.getN_pedido();
            String dt=""+pd.getData();
            String qtd =""+pd.getQtd();
            String[] linha={
num,pd.getProdutoNome(),pd.getClienteNome(),qtd,pd.getStatus(),dt
                
            } ;
               
          tableModel.addRow(linha);
           }
         tabela.setModel(tableModel);
           
    }else{
              
                    DefaultTableModel tableModel = new DefaultTableModel(colunas, 0);
         tabela.setModel(tableModel); 
              
          }
        
        
        
    }
    
    
    
    
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        prodbtn = new javax.swing.JButton();
        clibtn = new javax.swing.JButton();
        addPedidobtn = new javax.swing.JButton();
        revisarOrcbtn = new javax.swing.JButton();
        attbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(430, 345));
        setSize(new java.awt.Dimension(430, 305));

        jPanel1.setBackground(new java.awt.Color(148, 199, 182));
        jPanel1.setForeground(new java.awt.Color(148, 199, 182));
        jPanel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(237, 235, 230));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pedidos Recentes");

        tabela.setBackground(new java.awt.Color(255, 255, 255));
        tabela.setForeground(new java.awt.Color(0, 0, 0));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N°Pedido", "Produto", "Cliente", "Qtd", "Status", "Data de entrega"
            }
        ));
        tabela.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setMaxWidth(50);
            tabela.getColumnModel().getColumn(2).setMaxWidth(60);
            tabela.getColumnModel().getColumn(3).setMinWidth(40);
            tabela.getColumnModel().getColumn(3).setMaxWidth(41);
            tabela.getColumnModel().getColumn(4).setMaxWidth(60);
            tabela.getColumnModel().getColumn(5).setMinWidth(100);
        }

        prodbtn.setBackground(new java.awt.Color(230, 221, 220));
        prodbtn.setText("Produtos");
        prodbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodbtnActionPerformed(evt);
            }
        });

        clibtn.setBackground(new java.awt.Color(230, 221, 220));
        clibtn.setText("Clientes");
        clibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clibtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 594, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(prodbtn)
                        .addGap(55, 55, 55)
                        .addComponent(clibtn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodbtn)
                    .addComponent(clibtn))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        addPedidobtn.setBackground(new java.awt.Color(215, 220, 208));
        addPedidobtn.setText("Inserir novo pedido");
        addPedidobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPedidobtnActionPerformed(evt);
            }
        });

        revisarOrcbtn.setBackground(new java.awt.Color(214, 225, 199));
        revisarOrcbtn.setText("Revisar orçamentos");
        revisarOrcbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisarOrcbtnActionPerformed(evt);
            }
        });

        attbtn.setBackground(new java.awt.Color(214, 225, 199));
        attbtn.setText("Atualizar Status");
        attbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(revisarOrcbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addPedidobtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(attbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(revisarOrcbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                    .addComponent(addPedidobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attbtnActionPerformed
        /*int i;
        for(i=0;i<listapd.size();i++){
        */  
    int i=tabela.getSelectedRow();
    

        
        
        
      if(tabela.isRowSelected(i)){
        attStatus stt=new attStatus();
stt.setVisible(true);

stt.setrow(getrow());
      }else{
            
            JOptionPane.showMessageDialog(null, "Selecione um pedido na tabela");
      }

        
        
    }//GEN-LAST:event_attbtnActionPerformed

    private void revisarOrcbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisarOrcbtnActionPerformed
      TabelaOrcamentos to = new TabelaOrcamentos();
to.setVisible(true);
to.att();

dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_revisarOrcbtnActionPerformed

    private void addPedidobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPedidobtnActionPerformed

NovoPedido np = new NovoPedido();

np.setVisible(true);
     dispose();
        np.combocli();
        np.comboprod();
        
        
        
    }//GEN-LAST:event_addPedidobtnActionPerformed

    private void prodbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodbtnActionPerformed
        ProdutosView pv = new ProdutosView();
        pv.setVisible(true);
        dispose();
       pv.att();
    }//GEN-LAST:event_prodbtnActionPerformed

    private void clibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clibtnActionPerformed
ClienteView cv=new ClienteView();
cv.setVisible(true);

dispose();
cv.att();


    }//GEN-LAST:event_clibtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPedidobtn;
    private javax.swing.JButton attbtn;
    private javax.swing.JButton clibtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prodbtn;
    private javax.swing.JButton revisarOrcbtn;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
